Repository KaspervanM/WASP, pull requests merged in 2021-06, with the labels that each got.

#98 Fill in dashboard fields
  client/src/components/TheProgressBar.vue
  client/src/views/AddTask.vue
  client/src/views/Dashboard.vue
Labels: enhancement

#99 Viewtasks with drop down description and button for helping tasks.
  client/src/views/AddTask.vue
  client/src/views/ViewTasks.vue
Labels: enhancement

#102 Clarify tooltip
  client/src/App.vue
  client/src/views/AddTask.vue
Labels: documentation, help wanted

#103 Add examples
  examples/constants/euler.js
  examples/constants/liouville.js
  examples/constants/pi-chudnovsky-post-processing.js
  examples/constants/pi-chudnovsky.js
  examples/default.js
  server/src/app.ts
Labels: enhancement

#105 Guide page
  client/src/App.vue
  client/src/components/TheSidebar.vue
  client/src/router/index.ts
  client/src/services/taskService.ts
  client/src/views/About.vue
  client/src/views/AddTask.vue
  client/src/views/Guide.vue
  client/src/views/Home.vue
  client/src/views/ViewTasks.vue
Labels: documentation

#107 new factorial function
  examples/constants/euler.js
  examples/constants/liouville.js
  examples/constants/pi-chudnovsky.js
Labels: enhancement
