Repository KaspervanM/WASP, pull requests merged in 2021-05, with the labels that each got.

#79 Evan optimise communication
  client/src/App.vue
  client/src/components/TaskStarter.vue
  client/src/components/TheProgressBar.vue
  client/src/services/evaluateCode.ts
  client/src/services/taskService.ts
  client/src/views/AddTask.vue
  client/src/views/Dashboard.vue
  client/src/views/DeleteTask.vue
  client/src/views/ViewTasks.vue
  server/README.MD
  server/package-lock.json
  server/package.json
  server/src/app.ts
Labels: enhancement

#44 Evan ontwikkelen
  WASP ontwikkelingshandleiding.md
Labels: documentation

#82 Kaspervanm view results updated
  client/src/App.vue
  client/src/components/TheProgressBar.vue
  client/src/router/index.ts
  client/src/services/taskService.ts
  client/src/views/AddTask.vue
  client/src/views/Dashboard.vue
  client/src/views/Results.vue
  server/package-lock.json
  server/package.json
  server/src/app.ts
Labels: enhancement

#83 Evan export/import srv
  server/src/app.ts
Labels: enhancement

#84 Add vetur.config.js
  vetur.config.js
Labels: bug

#85 Secure code from users
  client/src/views/AddTask.vue
  server/src/app.ts
Labels: enhancement

#89 fix
  client/src/services/taskService.ts
  client/src/views/ViewTasks.vue
Labels: bug

#91 Upload code test
  client/src/views/AddTask.vue
  client/src/views/Results.vue
Labels: could have, enhancement

#87 Home page
  client/package-lock.json
  client/package.json
  client/src/App.vue
  client/src/assets/Diagram1.png
  client/src/assets/hide-the-pain-harold-why-you-should-not-use-stock-photos.jpg
  client/src/assets/logo-old.png
  client/src/components/TheSidebar.vue
  client/src/main.ts
  client/src/router/index.ts
  client/src/shims-tsx.d.ts
  client/src/shims-vue.d.ts
  client/src/types/shims-png.d.ts
  client/src/types/shims-tsx.d.ts
  client/src/types/shims-typer.d.ts
  client/src/types/shims-vue.d.ts
  client/src/views/Home.vue
  server/package-lock.json
Labels: enhancement

#95 Kaspervanm bigint return type
  client/src/components/TaskStarter.vue
  client/src/services/taskService.ts
  client/src/views/AddTask.vue
  server/src/app.ts
Labels: enhancement

#96 Evan fix delete tasks
  client/src/services/taskService.ts
  client/src/views/DeleteTask.vue
  server/src/app.ts
Labels: bug
